name: CI - Bilhetagem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install httpx


    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run Unit Tests
      run: pytest app/tests

    - name: Start API Server (background)
      run: |
        uvicorn run:app --port 8000 &
        sleep 5

    - name: Init Database
      run: |
        python -c "from database.init_db import init_db; init_db()"

    - name: Run Integration/TaaC Tests
      run: pytest tests/integrations

    - name: Stop API Server
      run: |
        pkill -f "uvicorn"